# Generated by Django 4.2.10 on 2026-02-11 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sentiment_label", models.CharField(max_length=20)),
                ("sentiment_score", models.FloatField()),
                ("sentiment_positive", models.FloatField(default=0.0)),
                ("sentiment_neutral", models.FloatField(default=0.0)),
                ("sentiment_negative", models.FloatField(default=0.0)),
                ("emotion_joy", models.FloatField(default=0.0)),
                ("emotion_sadness", models.FloatField(default=0.0)),
                ("emotion_anger", models.FloatField(default=0.0)),
                ("emotion_fear", models.FloatField(default=0.0)),
                ("emotion_surprise", models.FloatField(default=0.0)),
                ("emotion_neutral", models.FloatField(default=0.0)),
                ("personality_openness", models.IntegerField(default=50)),
                ("personality_conscientiousness", models.IntegerField(default=50)),
                ("personality_extraversion", models.IntegerField(default=50)),
                ("personality_agreeableness", models.IntegerField(default=50)),
                ("personality_neuroticism", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="api.post",
                    ),
                ),
            ],
        ),
    ]
