# Generated by Django 4.2.10 on 2026-02-16 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_posts_analyzed", models.IntegerField(default=0)),
                ("total_rewrites_generated", models.IntegerField(default=0)),
                ("languages_used", models.IntegerField(default=0)),
                ("avg_sentiment_improvement", models.FloatField(default=0.0)),
                ("emotional_stability", models.FloatField(default=0.0)),
                ("personality_growth", models.FloatField(default=0.0)),
                ("avg_rewrite_sentiment_change", models.FloatField(default=0.0)),
                ("avg_rewrite_positivity_increase", models.FloatField(default=0.0)),
                ("days_active", models.IntegerField(default=0)),
                ("average_posts_per_day", models.FloatField(default=0.0)),
                ("streak_days", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Metrics",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmotionalProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("avg_sentiment_score", models.FloatField(default=0.0)),
                ("avg_emotion_joy", models.FloatField(default=0.0)),
                ("avg_emotion_sadness", models.FloatField(default=0.0)),
                ("avg_emotion_anger", models.FloatField(default=0.0)),
                ("avg_emotion_fear", models.FloatField(default=0.0)),
                ("avg_emotion_surprise", models.FloatField(default=0.0)),
                ("avg_personality_openness", models.FloatField(default=0.0)),
                ("avg_personality_conscientiousness", models.FloatField(default=0.0)),
                ("avg_personality_extraversion", models.FloatField(default=0.0)),
                ("avg_personality_agreeableness", models.FloatField(default=0.0)),
                ("avg_personality_neuroticism", models.FloatField(default=0.0)),
                ("posts_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotional_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sentiment_label", models.CharField(max_length=20)),
                ("sentiment_score", models.FloatField()),
                ("sentiment_positive", models.FloatField(default=0.0)),
                ("sentiment_neutral", models.FloatField(default=0.0)),
                ("sentiment_negative", models.FloatField(default=0.0)),
                ("emotion_joy", models.FloatField(default=0.0)),
                ("emotion_sadness", models.FloatField(default=0.0)),
                ("emotion_anger", models.FloatField(default=0.0)),
                ("emotion_fear", models.FloatField(default=0.0)),
                ("emotion_surprise", models.FloatField(default=0.0)),
                ("emotion_neutral", models.FloatField(default=0.0)),
                ("personality_openness", models.IntegerField(default=50)),
                ("personality_conscientiousness", models.IntegerField(default=50)),
                ("personality_extraversion", models.IntegerField(default=50)),
                ("personality_agreeableness", models.IntegerField(default=50)),
                ("personality_neuroticism", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="api.post",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "-created_at"], name="api_post_user_id_2486e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emotionalprogress",
            index=models.Index(
                fields=["user", "-date"], name="api_emotion_user_id_e677bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emotionalprogress",
            unique_together={("user", "date")},
        ),
    ]
