# Generated by Django 4.2.10 on 2026-02-21 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('rewritten_text', models.TextField(default='')),
                ('goal', models.CharField(default='more_positive', max_length=40)),
                ('source_language', models.CharField(default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='detected_language_type',
            field=models.CharField(default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='detected_tone',
            field=models.CharField(default='friendly', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='intent',
            field=models.CharField(default='informational', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='informational', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'post_type'], name='api_post_user_id_a0ec4d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'detected_language_type'], name='api_post_user_id_5eeea7_idx'),
        ),
        migrations.AddField(
            model_name='rewriterecord',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewrites', to='api.post'),
        ),
        migrations.AddField(
            model_name='rewriterecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rewriterecord',
            index=models.Index(fields=['user', '-created_at'], name='api_rewrite_user_id_e0c945_idx'),
        ),
        migrations.AddIndex(
            model_name='rewriterecord',
            index=models.Index(fields=['user', 'goal'], name='api_rewrite_user_id_ed86a0_idx'),
        ),
    ]
